version: '3.9'
services:
  express:
    build:
      context: ./
    ports: 
      - "5000:8080"
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command:
      - nodemon
      - index.js
      - -L